/* Generated by Yosys 0.68+71 (git sha1 dbe5b7c03-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

module \$paramod\spi_master\CLK_DIV=s32'00000000000000000000000000000100 (clk, rst, start, tx_data, miso, rx_data, busy, done, sclk, mosi, cs_n);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  input miso;
  wire miso;
  output [7:0] rx_data;
  reg [7:0] rx_data;
  output busy;
  reg busy;
  output done;
  reg done;
  output sclk;
  reg sclk;
  output mosi;
  reg mosi;
  output cs_n;
  reg cs_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  reg [2:0] bit_count;
  reg [15:0] clk_count;
  reg [6:0] rx_shift;
  reg [6:0] tx_shift;
  assign _019_ = busy ? tx_shift[1] : tx_data[2];
  assign _018_ = busy ? tx_shift[0] : tx_data[1];
  assign _017_ = tx_data[0] & ~(busy);
  assign _015_ = busy & rx_shift[4];
  assign _014_ = busy & rx_shift[3];
  assign _013_ = busy & rx_shift[2];
  assign _012_ = busy & rx_shift[1];
  assign _011_ = busy & rx_shift[0];
  assign _010_ = busy & miso;
  assign _024_ = bit_count[1] & bit_count[0];
  assign _025_ = bit_count[1] | bit_count[0];
  assign _026_ = busy & _025_;
  assign _110_ = _026_ & ~(_024_);
  assign _109_ = busy & ~(bit_count[0]);
  assign _027_ = clk_count[1] & clk_count[0];
  assign _028_ = clk_count[2] & _027_;
  assign _029_ = clk_count[3] & _028_;
  assign _030_ = clk_count[4] & _029_;
  assign _031_ = clk_count[5] & _030_;
  assign _032_ = clk_count[6] & _031_;
  assign _033_ = clk_count[7] & _032_;
  assign _034_ = clk_count[8] & _033_;
  assign _035_ = clk_count[9] & _034_;
  assign _036_ = clk_count[10] & _035_;
  assign _037_ = clk_count[11] & _036_;
  assign _038_ = clk_count[12] & _037_;
  assign _039_ = clk_count[13] & _038_;
  assign _040_ = ~(clk_count[14] & _039_);
  assign _041_ = clk_count[14] | _039_;
  assign _042_ = busy & _041_;
  assign _098_ = _040_ & _042_;
  assign _043_ = clk_count[13] | _038_;
  assign _044_ = busy & _043_;
  assign _097_ = _044_ & ~(_039_);
  assign _045_ = clk_count[12] | _037_;
  assign _046_ = busy & _045_;
  assign _096_ = _046_ & ~(_038_);
  assign _047_ = clk_count[11] | _036_;
  assign _048_ = busy & _047_;
  assign _095_ = _048_ & ~(_037_);
  assign _049_ = clk_count[10] | _035_;
  assign _050_ = busy & _049_;
  assign _094_ = _050_ & ~(_036_);
  assign _051_ = clk_count[9] | _034_;
  assign _052_ = busy & _051_;
  assign _108_ = _052_ & ~(_035_);
  assign _053_ = clk_count[8] | _033_;
  assign _054_ = busy & _053_;
  assign _107_ = _054_ & ~(_034_);
  assign _055_ = clk_count[7] | _032_;
  assign _056_ = busy & _055_;
  assign _106_ = _056_ & ~(_033_);
  assign _057_ = clk_count[6] | _031_;
  assign _058_ = busy & _057_;
  assign _105_ = _058_ & ~(_032_);
  assign _059_ = clk_count[5] | _030_;
  assign _060_ = busy & _059_;
  assign _104_ = _060_ & ~(_031_);
  assign _061_ = clk_count[4] | _029_;
  assign _062_ = busy & _061_;
  assign _103_ = _062_ & ~(_030_);
  assign _063_ = clk_count[3] | _028_;
  assign _064_ = busy & _063_;
  assign _102_ = _064_ & ~(_029_);
  assign _065_ = ~(clk_count[13] | clk_count[10]);
  assign _066_ = ~(clk_count[12] | clk_count[11]);
  assign _067_ = _065_ & _066_;
  assign _068_ = ~(clk_count[14] | clk_count[15]);
  assign _069_ = _027_ & _068_;
  assign _070_ = _067_ & _069_;
  assign _071_ = ~(clk_count[4] | clk_count[5]);
  assign _072_ = ~(clk_count[2] | clk_count[3]);
  assign _073_ = _071_ & _072_;
  assign _074_ = ~(clk_count[6] | clk_count[7]);
  assign _075_ = ~(clk_count[8] | clk_count[9]);
  assign _076_ = _074_ & _075_;
  assign _077_ = _073_ & _076_;
  assign _078_ = _070_ & _077_;
  assign _079_ = busy & ~(_078_);
  assign _080_ = clk_count[2] ^ _027_;
  assign _101_ = _079_ & _080_;
  assign _081_ = clk_count[1] | clk_count[0];
  assign _082_ = busy & _081_;
  assign _100_ = _082_ & ~(_027_);
  assign _093_ = busy & ~(clk_count[0]);
  assign _021_ = busy ? tx_shift[3] : tx_data[4];
  assign _009_ = bit_count[2] & _024_;
  assign _008_ = busy & ~(sclk);
  assign _000_ = busy | start;
  assign _002_ = busy ? _078_ : start;
  assign _020_ = busy ? tx_shift[2] : tx_data[3];
  assign _022_ = busy ? tx_shift[4] : tx_data[5];
  assign _003_ = _002_ & ~(_008_);
  assign _083_ = ~(busy & _009_);
  assign _005_ = _003_ & _083_;
  assign _023_ = busy ? tx_shift[5] : tx_data[6];
  assign _084_ = busy | ~(tx_data[7]);
  assign _085_ = busy & ~(_009_);
  assign _086_ = ~(tx_shift[6] & _085_);
  assign _112_ = ~(_084_ & _086_);
  assign _087_ = busy & sclk;
  assign _088_ = _078_ & _009_;
  assign _089_ = ~(_087_ & _088_);
  assign _113_ = _000_ & _089_;
  assign _090_ = _087_ & ~(rst);
  assign _007_ = ~(_078_ & _090_);
  assign _004_ = _003_ & ~(_085_);
  assign _001_ = _008_ & _088_;
  assign _016_ = busy & rx_shift[5];
  assign _091_ = bit_count[2] | _024_;
  assign _111_ = _085_ & _091_;
  assign _092_ = ~(clk_count[15] ^ _040_);
  assign _099_ = busy & _092_;
  assign _006_ = _002_ & ~(_087_);
  always @(posedge clk)
    if (rst) bit_count[0] <= 1'h0;
    else if (_005_) bit_count[0] <= _109_;
  always @(posedge clk)
    if (rst) bit_count[1] <= 1'h0;
    else if (_005_) bit_count[1] <= _110_;
  always @(posedge clk)
    if (rst) bit_count[2] <= 1'h0;
    else if (_005_) bit_count[2] <= _111_;
  always @(posedge clk)
    if (rst) rx_shift[0] <= 1'h0;
    else if (_006_) rx_shift[0] <= _010_;
  always @(posedge clk)
    if (rst) rx_shift[1] <= 1'h0;
    else if (_006_) rx_shift[1] <= _011_;
  always @(posedge clk)
    if (rst) rx_shift[2] <= 1'h0;
    else if (_006_) rx_shift[2] <= _012_;
  always @(posedge clk)
    if (rst) rx_shift[3] <= 1'h0;
    else if (_006_) rx_shift[3] <= _013_;
  always @(posedge clk)
    if (rst) rx_shift[4] <= 1'h0;
    else if (_006_) rx_shift[4] <= _014_;
  always @(posedge clk)
    if (rst) rx_shift[5] <= 1'h0;
    else if (_006_) rx_shift[5] <= _015_;
  always @(posedge clk)
    if (rst) rx_shift[6] <= 1'h0;
    else if (_006_) rx_shift[6] <= _016_;
  always @(posedge clk)
    if (rst) tx_shift[0] <= 1'h0;
    else if (_005_) tx_shift[0] <= _017_;
  always @(posedge clk)
    if (rst) tx_shift[1] <= 1'h0;
    else if (_005_) tx_shift[1] <= _018_;
  always @(posedge clk)
    if (rst) tx_shift[2] <= 1'h0;
    else if (_005_) tx_shift[2] <= _019_;
  always @(posedge clk)
    if (rst) tx_shift[3] <= 1'h0;
    else if (_005_) tx_shift[3] <= _020_;
  always @(posedge clk)
    if (rst) tx_shift[4] <= 1'h0;
    else if (_005_) tx_shift[4] <= _021_;
  always @(posedge clk)
    if (rst) tx_shift[5] <= 1'h0;
    else if (_005_) tx_shift[5] <= _022_;
  always @(posedge clk)
    if (rst) tx_shift[6] <= 1'h0;
    else if (_005_) tx_shift[6] <= _023_;
  always @(posedge clk)
    if (rst) cs_n <= 1'h1;
    else if (_004_) cs_n <= busy;
  always @(posedge clk)
    if (rst) mosi <= 1'h0;
    else if (_003_) mosi <= _112_;
  always @(posedge clk)
    if (rst) sclk <= 1'h0;
    else if (_002_) sclk <= _008_;
  always @(posedge clk)
    if (_007_) done <= 1'h0;
    else done <= _009_;
  always @(posedge clk)
    if (rst) busy <= 1'h0;
    else busy <= _113_;
  always @(posedge clk)
    if (rst) rx_data[0] <= 1'h0;
    else if (_001_) rx_data[0] <= miso;
  always @(posedge clk)
    if (rst) rx_data[1] <= 1'h0;
    else if (_001_) rx_data[1] <= rx_shift[0];
  always @(posedge clk)
    if (rst) rx_data[2] <= 1'h0;
    else if (_001_) rx_data[2] <= rx_shift[1];
  always @(posedge clk)
    if (rst) rx_data[3] <= 1'h0;
    else if (_001_) rx_data[3] <= rx_shift[2];
  always @(posedge clk)
    if (rst) rx_data[4] <= 1'h0;
    else if (_001_) rx_data[4] <= rx_shift[3];
  always @(posedge clk)
    if (rst) rx_data[5] <= 1'h0;
    else if (_001_) rx_data[5] <= rx_shift[4];
  always @(posedge clk)
    if (rst) rx_data[6] <= 1'h0;
    else if (_001_) rx_data[6] <= rx_shift[5];
  always @(posedge clk)
    if (rst) rx_data[7] <= 1'h0;
    else if (_001_) rx_data[7] <= rx_shift[6];
  always @(posedge clk)
    if (rst) clk_count[0] <= 1'h0;
    else if (_000_) clk_count[0] <= _093_;
  always @(posedge clk)
    if (rst) clk_count[1] <= 1'h0;
    else if (_000_) clk_count[1] <= _100_;
  always @(posedge clk)
    if (rst) clk_count[2] <= 1'h0;
    else if (_000_) clk_count[2] <= _101_;
  always @(posedge clk)
    if (rst) clk_count[3] <= 1'h0;
    else if (_000_) clk_count[3] <= _102_;
  always @(posedge clk)
    if (rst) clk_count[4] <= 1'h0;
    else if (_000_) clk_count[4] <= _103_;
  always @(posedge clk)
    if (rst) clk_count[5] <= 1'h0;
    else if (_000_) clk_count[5] <= _104_;
  always @(posedge clk)
    if (rst) clk_count[6] <= 1'h0;
    else if (_000_) clk_count[6] <= _105_;
  always @(posedge clk)
    if (rst) clk_count[7] <= 1'h0;
    else if (_000_) clk_count[7] <= _106_;
  always @(posedge clk)
    if (rst) clk_count[8] <= 1'h0;
    else if (_000_) clk_count[8] <= _107_;
  always @(posedge clk)
    if (rst) clk_count[9] <= 1'h0;
    else if (_000_) clk_count[9] <= _108_;
  always @(posedge clk)
    if (rst) clk_count[10] <= 1'h0;
    else if (_000_) clk_count[10] <= _094_;
  always @(posedge clk)
    if (rst) clk_count[11] <= 1'h0;
    else if (_000_) clk_count[11] <= _095_;
  always @(posedge clk)
    if (rst) clk_count[12] <= 1'h0;
    else if (_000_) clk_count[12] <= _096_;
  always @(posedge clk)
    if (rst) clk_count[13] <= 1'h0;
    else if (_000_) clk_count[13] <= _097_;
  always @(posedge clk)
    if (rst) clk_count[14] <= 1'h0;
    else if (_000_) clk_count[14] <= _098_;
  always @(posedge clk)
    if (rst) clk_count[15] <= 1'h0;
    else if (_000_) clk_count[15] <= _099_;
endmodule

module spi_master_slave_top(clk, rst, start, master_tx_data, slave_tx_data, master_rx_data, slave_rx_data, busy, done, spi_sclk, spi_mosi, spi_miso, spi_cs_n);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input [7:0] master_tx_data;
  wire [7:0] master_tx_data;
  input [7:0] slave_tx_data;
  wire [7:0] slave_tx_data;
  output [7:0] master_rx_data;
  wire [7:0] master_rx_data;
  output [7:0] slave_rx_data;
  wire [7:0] slave_rx_data;
  output busy;
  wire busy;
  output done;
  wire done;
  output spi_sclk;
  wire spi_sclk;
  output spi_mosi;
  wire spi_mosi;
  output spi_miso;
  wire spi_miso;
  output spi_cs_n;
  wire spi_cs_n;
  wire master_busy;
  wire master_cs_n;
  wire master_done;
  wire master_mosi;
  wire [7:0] master_rx;
  wire master_sclk;
  wire slave_done;
  wire slave_miso;
  wire [7:0] slave_rx;
  \$paramod\spi_master\CLK_DIV=s32'00000000000000000000000000000100  master_inst (
    .busy(master_busy),
    .clk(clk),
    .cs_n(master_cs_n),
    .done(master_done),
    .miso(slave_miso),
    .mosi(master_mosi),
    .rst(rst),
    .rx_data(master_rx),
    .sclk(master_sclk),
    .start(start),
    .tx_data(master_tx_data)
  );
  spi_slave slave_inst (
    .clk(clk),
    .cs_n(master_cs_n),
    .done(slave_done),
    .miso(slave_miso),
    .mosi(master_mosi),
    .rst(rst),
    .rx_data(slave_rx),
    .sclk(master_sclk),
    .tx_data(slave_tx_data)
  );
  assign spi_cs_n = master_cs_n;
  assign spi_miso = slave_miso;
  assign spi_mosi = master_mosi;
  assign spi_sclk = master_sclk;
  assign done = master_done;
  assign busy = master_busy;
  assign slave_rx_data = slave_rx;
  assign master_rx_data = master_rx;
endmodule

module spi_slave(clk, rst, cs_n, sclk, mosi, tx_data, miso, rx_data, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input cs_n;
  wire cs_n;
  input sclk;
  wire sclk;
  input mosi;
  wire mosi;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output miso;
  reg miso;
  output [7:0] rx_data;
  reg [7:0] rx_data;
  output done;
  reg done;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [2:0] _27_;
  wire [2:0] _28_;
  reg [2:0] bit_count;
  reg cs_n_d;
  reg [6:0] rx_shift;
  reg sclk_d;
  reg [6:0] tx_shift;
  assign _16_ = ~cs_n;
  assign _27_[0] = ~bit_count[0];
  assign _17_ = cs_n_d & ~(cs_n);
  assign _12_ = _17_ ? tx_data[4] : tx_shift[3];
  assign _11_ = _17_ ? tx_data[3] : tx_shift[2];
  assign _10_ = _17_ ? tx_data[2] : tx_shift[1];
  assign _18_ = bit_count[1] & bit_count[0];
  assign _15_ = bit_count[2] & _18_;
  assign _09_ = _17_ ? tx_data[1] : tx_shift[0];
  assign _28_[1] = bit_count[1] ^ bit_count[0];
  assign _08_ = tx_data[0] & _17_;
  assign _13_ = _17_ ? tx_data[5] : tx_shift[4];
  assign _28_[2] = bit_count[2] ^ _18_;
  assign _14_ = _17_ ? tx_data[6] : tx_shift[5];
  assign _19_ = sclk | ~(sclk_d);
  assign _20_ = _15_ | _19_;
  assign _04_ = ~_20_;
  assign _21_ = _17_ | ~(_20_);
  assign _00_ = cs_n | _21_;
  assign _22_ = sclk & ~(sclk_d);
  assign _03_ = _16_ & _22_;
  assign _23_ = _15_ & _03_;
  assign _01_ = _23_ & ~(_17_);
  assign _06_ = rst | _17_;
  assign _24_ = ~_06_;
  assign _07_ = cs_n | _06_;
  assign _05_ = ~(_03_ & _24_);
  assign _02_ = _16_ & _21_;
  assign _25_ = cs_n_d ? tx_data[7] : tx_shift[6];
  assign _26_ = _16_ & _25_;
  always @(posedge clk)
    if (_07_) bit_count[0] <= 1'h0;
    else if (_04_) bit_count[0] <= _27_[0];
  always @(posedge clk)
    if (_07_) bit_count[1] <= 1'h0;
    else if (_04_) bit_count[1] <= _28_[1];
  always @(posedge clk)
    if (_07_) bit_count[2] <= 1'h0;
    else if (_04_) bit_count[2] <= _28_[2];
  always @(posedge clk)
    if (_06_) rx_shift[0] <= 1'h0;
    else if (_03_) rx_shift[0] <= mosi;
  always @(posedge clk)
    if (_06_) rx_shift[1] <= 1'h0;
    else if (_03_) rx_shift[1] <= rx_shift[0];
  always @(posedge clk)
    if (_06_) rx_shift[2] <= 1'h0;
    else if (_03_) rx_shift[2] <= rx_shift[1];
  always @(posedge clk)
    if (_06_) rx_shift[3] <= 1'h0;
    else if (_03_) rx_shift[3] <= rx_shift[2];
  always @(posedge clk)
    if (_06_) rx_shift[4] <= 1'h0;
    else if (_03_) rx_shift[4] <= rx_shift[3];
  always @(posedge clk)
    if (_06_) rx_shift[5] <= 1'h0;
    else if (_03_) rx_shift[5] <= rx_shift[4];
  always @(posedge clk)
    if (_06_) rx_shift[6] <= 1'h0;
    else if (_03_) rx_shift[6] <= rx_shift[5];
  always @(posedge clk)
    if (rst) tx_shift[0] <= 1'h0;
    else if (_02_) tx_shift[0] <= _08_;
  always @(posedge clk)
    if (rst) tx_shift[1] <= 1'h0;
    else if (_02_) tx_shift[1] <= _09_;
  always @(posedge clk)
    if (rst) tx_shift[2] <= 1'h0;
    else if (_02_) tx_shift[2] <= _10_;
  always @(posedge clk)
    if (rst) tx_shift[3] <= 1'h0;
    else if (_02_) tx_shift[3] <= _11_;
  always @(posedge clk)
    if (rst) tx_shift[4] <= 1'h0;
    else if (_02_) tx_shift[4] <= _12_;
  always @(posedge clk)
    if (rst) tx_shift[5] <= 1'h0;
    else if (_02_) tx_shift[5] <= _13_;
  always @(posedge clk)
    if (rst) tx_shift[6] <= 1'h0;
    else if (_02_) tx_shift[6] <= _14_;
  always @(posedge clk)
    if (_05_) done <= 1'h0;
    else done <= _15_;
  always @(posedge clk)
    if (rst) rx_data[0] <= 1'h0;
    else if (_01_) rx_data[0] <= mosi;
  always @(posedge clk)
    if (rst) rx_data[1] <= 1'h0;
    else if (_01_) rx_data[1] <= rx_shift[0];
  always @(posedge clk)
    if (rst) rx_data[2] <= 1'h0;
    else if (_01_) rx_data[2] <= rx_shift[1];
  always @(posedge clk)
    if (rst) rx_data[3] <= 1'h0;
    else if (_01_) rx_data[3] <= rx_shift[2];
  always @(posedge clk)
    if (rst) rx_data[4] <= 1'h0;
    else if (_01_) rx_data[4] <= rx_shift[3];
  always @(posedge clk)
    if (rst) rx_data[5] <= 1'h0;
    else if (_01_) rx_data[5] <= rx_shift[4];
  always @(posedge clk)
    if (rst) rx_data[6] <= 1'h0;
    else if (_01_) rx_data[6] <= rx_shift[5];
  always @(posedge clk)
    if (rst) rx_data[7] <= 1'h0;
    else if (_01_) rx_data[7] <= rx_shift[6];
  always @(posedge clk)
    if (rst) miso <= 1'h0;
    else if (_00_) miso <= _26_;
  always @(posedge clk)
    if (rst) sclk_d <= 1'h0;
    else sclk_d <= sclk;
  always @(posedge clk)
    if (rst) cs_n_d <= 1'h1;
    else cs_n_d <= cs_n;
  assign _27_[2:1] = bit_count[2:1];
  assign _28_[0] = _27_[0];
endmodule
